/*
 * This file is generated by jOOQ.
*/
package ru.ibase.fbjavaex.exampledb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ru.ibase.fbjavaex.exampledb.tables.Migrations;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MigrationsRecord extends TableRecordImpl<MigrationsRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = -1043349343;

    /**
     * Setter for <code>migrations.migration</code>.
     */
    public void setMigration(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>migrations.migration</code>.
     */
    public String getMigration() {
        return (String) get(0);
    }

    /**
     * Setter for <code>migrations.batch</code>.
     */
    public void setBatch(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>migrations.batch</code>.
     */
    public Integer getBatch() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Migrations.MIGRATIONS.MIGRATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Migrations.MIGRATIONS.BATCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getMigration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getBatch();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMigration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBatch();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MigrationsRecord value1(String value) {
        setMigration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MigrationsRecord value2(Integer value) {
        setBatch(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MigrationsRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MigrationsRecord
     */
    public MigrationsRecord() {
        super(Migrations.MIGRATIONS);
    }

    /**
     * Create a detached, initialised MigrationsRecord
     */
    public MigrationsRecord(String migration, Integer batch) {
        super(Migrations.MIGRATIONS);

        set(0, migration);
        set(1, batch);
    }
}
