/*
 * This file is generated by jOOQ.
*/
package ru.ibase.fbjavaex.exampledb.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.ibase.fbjavaex.exampledb.DefaultSchema;
import ru.ibase.fbjavaex.exampledb.tables.records.MigrationsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Migrations extends TableImpl<MigrationsRecord> {

    private static final long serialVersionUID = 1249749757;

    /**
     * The reference instance of <code>migrations</code>
     */
    public static final Migrations MIGRATIONS = new Migrations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MigrationsRecord> getRecordType() {
        return MigrationsRecord.class;
    }

    /**
     * The column <code>migrations.migration</code>.
     */
    public final TableField<MigrationsRecord, String> MIGRATION = createField("migration", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>migrations.batch</code>.
     */
    public final TableField<MigrationsRecord, Integer> BATCH = createField("batch", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>migrations</code> table reference
     */
    public Migrations() {
        this(DSL.name("migrations"), null);
    }

    /**
     * Create an aliased <code>migrations</code> table reference
     */
    public Migrations(String alias) {
        this(DSL.name(alias), MIGRATIONS);
    }

    /**
     * Create an aliased <code>migrations</code> table reference
     */
    public Migrations(Name alias) {
        this(alias, MIGRATIONS);
    }

    private Migrations(Name alias, Table<MigrationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Migrations(Name alias, Table<MigrationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Migrations as(String alias) {
        return new Migrations(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Migrations as(Name alias) {
        return new Migrations(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Migrations rename(String name) {
        return new Migrations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Migrations rename(Name name) {
        return new Migrations(name, null);
    }
}
